### PR TITLE
Update .npmignore

### PR DESCRIPTION
**Pull request by xwartz**
Should ignore __tests__ files

### CODE REVIEW

**Comment by sunnylqm** [comment]
why?

**Comment by xwartz** [comment]
It's useless, and may causes XCode compile failed.

see more https://facebook.github.io/react-native/docs/troubleshooting.html#argument-list-too-long-recursive-header-expansion-failed

**Comment by sunnylqm** [comment]
I've never hit an error caused by this, can you show me one? Well, since this commit does no harm, I'll merge it.

**Comment by xwartz** [comment]
I encountered this issue when I using [react-native-permissions](https://github.com/yonahforst/react-native-permissions).

**Comment by xwartz** [comment]
Xcode error like this

image

**Pull request merged**
